<?php

/**
 * This is a list of all the providers from https://github.com/SocialiteProviders/socialiteproviders.github.io
 */
return [
    // Default Socialite
    'facebook'        => ['repo' => 'laravel/socialite', 'icon' => 'fa-facebook-square'],
    'twitter'         => ['repo' => 'laravel/socialite', 'icon' => 'fa-twitter-square'],
    'google'          => ['repo' => 'laravel/socialite', 'icon' => 'fa-google'],
    'github'          => ['repo' => 'laravel/socialite', 'icon' => 'fa-github-square'],

    // SocialiteProviders
    '23andme'         => ['repo' => 'socialiteProviders/23andme', 'icon' => 'fa-square'],
    '37signals'       => ['repo' => 'socialiteProviders/37signals', 'icon' => 'fa-square'],
    '500px'           => ['repo' => 'socialiteProviders/500px', 'icon' => 'fa-square'],
    'AngelList'       => ['repo' => 'socialiteProviders/AngelList', 'icon' => 'fa-square'],
    'App.net'         => ['repo' => 'socialiteProviders/App.net', 'icon' => 'fa-square'],
    'Asana'           => ['repo' => 'socialiteProviders/Asana', 'icon' => 'fa-square'],
    'Bit.ly'          => ['repo' => 'socialiteProviders/Bit.ly', 'icon' => 'fa-square'],
    'Box'             => ['repo' => 'socialiteProviders/Box', 'icon' => 'fa-square'],
    'Buffer'          => ['repo' => 'socialiteProviders/Buffer', 'icon' => 'fa-square'],
    'CampaignMonitor' => ['repo' => 'socialiteProviders/CampaignMonitor', 'icon' => 'fa-square'],
    'Cheddar'         => ['repo' => 'socialiteProviders/Cheddar', 'icon' => 'fa-square'],
    'Coinbase'        => ['repo' => 'socialiteProviders/Coinbase', 'icon' => 'fa-square'],
    'ConstantContact' => ['repo' => 'socialiteProviders/ConstantContact', 'icon' => 'fa-square'],
    'Dailymile'       => ['repo' => 'socialiteProviders/Dailymile', 'icon' => 'fa-square'],
    'Dailymotion'     => ['repo' => 'socialiteProviders/Dailymotion', 'icon' => 'fa-square'],
    'Deezer'          => ['repo' => 'socialiteProviders/Deezer', 'icon' => 'fa-square'],
    'DigitalOcean'    => ['repo' => 'socialiteProviders/DigitalOcean', 'icon' => 'fa-square'],
    'Disqus'          => ['repo' => 'socialiteProviders/Disqus', 'icon' => 'fa-square'],
    'Dribbble'        => ['repo' => 'socialiteProviders/Dribbble', 'icon' => 'fa-square'],
    'Dropbox'         => ['repo' => 'socialiteProviders/Dropbox', 'icon' => 'fa-square'],
    'Envato'          => ['repo' => 'socialiteProviders/Envato', 'icon' => 'fa-square'],
    'Eventbrite'      => ['repo' => 'socialiteProviders/Eventbrite', 'icon' => 'fa-square'],
    'Everyplay'       => ['repo' => 'socialiteProviders/Everyplay', 'icon' => 'fa-square'],
    'EyeEm'           => ['repo' => 'socialiteProviders/EyeEm', 'icon' => 'fa-square'],
    'Fitbit'          => ['repo' => 'socialiteProviders/Fitbit', 'icon' => 'fa-square'],
    'Flickr'          => ['repo' => 'socialiteProviders/Flickr', 'icon' => 'fa-square'],
    'Foursquare'      => ['repo' => 'socialiteProviders/Foursquare', 'icon' => 'fa-square'],
    'Goodreads'       => ['repo' => 'socialiteProviders/Goodreads', 'icon' => 'fa-square'],
    'GooglePlus'      => ['repo' => 'socialiteProviders/GooglePlus', 'icon' => 'fa-google-plus-square'],
    'Heroku'          => ['repo' => 'socialiteProviders/Heroku', 'icon' => 'fa-square'],
    'HumanApi'        => ['repo' => 'socialiteProviders/HumanApi', 'icon' => 'fa-square'],
    'Imgur'           => ['repo' => 'socialiteProviders/Imgur', 'icon' => 'fa-square'],
    'Instagram'       => ['repo' => 'socialiteProviders/Instagram', 'icon' => 'fa-square'],
    'Jawbone'         => ['repo' => 'socialiteProviders/Jawbone', 'icon' => 'fa-square'],
    'Jira'            => ['repo' => 'socialiteProviders/Jira', 'icon' => 'fa-square'],
    'LinkedIn'        => ['repo' => 'socialiteProviders/LinkedIn', 'icon' => 'fa-linkedin-square'],
    'MailChimp'       => ['repo' => 'socialiteProviders/MailChimp', 'icon' => 'fa-square'],
    'Meetup'          => ['repo' => 'socialiteProviders/Meetup', 'icon' => 'fa-square'],
    'MicrosoftLive'   => ['repo' => 'socialiteProviders/MicrosoftLive', 'icon' => 'fa-square'],
    'Mixcloud'        => ['repo' => 'socialiteProviders/Mixcloud', 'icon' => 'fa-square'],
    'PayPal'          => ['repo' => 'socialiteProviders/PayPal', 'icon' => 'fa-paypal'],
    'PayPalSandbox'   => ['repo' => 'socialiteProviders/PayPalSandbox', 'icon' => 'fa-paypal'],
    'Paymill'         => ['repo' => 'socialiteProviders/Paymill', 'icon' => 'fa-square'],
    'Podio'           => ['repo' => 'socialiteProviders/Podio', 'icon' => 'fa-square'],
    'Pushbullet'      => ['repo' => 'socialiteProviders/Pushbullet', 'icon' => 'fa-square'],
    'Rdio'            => ['repo' => 'socialiteProviders/Rdio', 'icon' => 'fa-square'],
    'Readability'     => ['repo' => 'socialiteProviders/Readability', 'icon' => 'fa-square'],
    'Reddit'          => ['repo' => 'socialiteProviders/Reddit', 'icon' => 'fa-reddit'],
    'RunKeeper'       => ['repo' => 'socialiteProviders/RunKeeper', 'icon' => 'fa-square'],
    'Slack'           => ['repo' => 'socialiteProviders/Slack', 'icon' => 'fa-slack'],
    'SoundCloud'      => ['repo' => 'socialiteProviders/SoundCloud', 'icon' => 'fa-soundcloud'],
    'Spotify'         => ['repo' => 'socialiteProviders/Spotify', 'icon' => 'fa-spotify'],
    'StackExchange'   => ['repo' => 'socialiteProviders/StackExchange', 'icon' => 'fa-square'],
    'StockTwits'      => ['repo' => 'socialiteProviders/StockTwits', 'icon' => 'fa-square'],
    'Strava'          => ['repo' => 'socialiteProviders/Strava', 'icon' => 'fa-square'],
    'Stripe'          => ['repo' => 'socialiteProviders/Stripe', 'icon' => 'fa-square'],
    'Trello'          => ['repo' => 'socialiteProviders/Trello', 'icon' => 'fa-trello'],
    'Tumblr'          => ['repo' => 'socialiteProviders/Tumblr', 'icon' => 'fa-square'],
    'Twitch'          => ['repo' => 'socialiteProviders/Twitch', 'icon' => 'fa-square'],
    'Uber'            => ['repo' => 'socialiteProviders/Uber', 'icon' => 'fa-square'],
    'VKontakte'       => ['repo' => 'socialiteProviders/VKontakte', 'icon' => 'fa-square'],
    'VersionOne'      => ['repo' => 'socialiteProviders/VersionOne', 'icon' => 'fa-square'],
    'Vimeo'           => ['repo' => 'socialiteProviders/Vimeo', 'icon' => 'fa-square'],
    'WordPress'       => ['repo' => 'socialiteProviders/WordPress', 'icon' => 'fa-square'],
    'Xing'            => ['repo' => 'socialiteProviders/Xing', 'icon' => 'fa-square'],
    'Yammer'          => ['repo' => 'socialiteProviders/Yammer', 'icon' => 'fa-square'],
    'Yandex'          => ['repo' => 'socialiteProviders/Yandex', 'icon' => 'fa-square'],
    'YouTube'         => ['repo' => 'socialiteProviders/YouTube', 'icon' => 'fa-youtube-square'],
    'Zendesk'         => ['repo' => 'socialiteProviders/Zendesk', 'icon' => 'fa-square'],
    'deviantART'      => ['repo' => 'socialiteProviders/deviantART', 'icon' => 'fa-deviantart'],
    'xREL'            => ['repo' => 'socialiteProviders/xREL', 'icon' => 'fa-square'],

];
